name: Deploy

on: deployment

jobs:
  deploy:
    if: github.event.deployment.environment == 'production'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GAUGEBOT_GITHUB_TOKEN }}'
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Install hub
        uses: geertvdc/setup-hub@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.100

      - name: Build artifacts
        run: |
          ./run.sh package

      - name: update
        run: |
          cd artifacts
          if [ -z "$version" ]; then
            version=$(ls gauge-dotnet* | head -1 | sed "s/\.[^\.]*$//" | sed "s/gauge-dotnet-//" | sed | sed "s/-[a-z]*\.[a-z0-9_]*$//");
          fi
          echo "::set-env name=VERSION::$version"
          artifacts=()
          dir=`pwd`
          for i in `ls`; do
            artifacts+="$dir/$i "
          done
          cd ..

          echo "---------------------------"
          echo "Updating release v$version"
          echo "---------------------------"

          echo -e "Gauge Dotnet v$version\n\n" > desc.txt

          release_description=$(ruby -e "$(curl -sSfL https://github.com/getgauge/gauge/raw/master/build/create_release_text.rb)" gauge-dotnet getgauge)

          echo "$release_description" >> desc.txt

          echo "Creating new draft for release v$version"
          hub release create -d -F ./desc.txt "v$version"

          rm -rf desc.txt

          echo "Start uploading assets..."
          for i in `ls $artifacts`; do
              hub release edit -m "" -a $i "v$version"
              if [ $? -ne 0 ];then
                  exit 1
              fi
          done

      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/status@master'
        with:
          state: 'success'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/status@master'
        with:
          state: 'failure'
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Update metadata in gauge-repository
        run: |
          git clone https://github.com/getgauge/gauge-repository.git
          cd gauge-repository
          python update_metadata.py dotnet $VERSION
          commit_message=$(echo -e "Update dotnet to v$VERSION")
          git commit -am "$commit_message"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/getgauge/gauge-repository.git" master
